### PR TITLE
Add typescript type declaration file

### PR DESCRIPTION
**Pull request by gillchristian**
This PR adds TypeScript declaration file.

### CODE REVIEW

**Comment by gillchristian** [comment]
@misund sorry to bother you with this, do you plan to merge it?

**Comment by misund** [comment]
I apologize for making you wait. Thank you for the contribution!

**Comment by misund** [comment]
I'll publish 1.0.0 later today.

**Comment by gillchristian** [comment]
No worries and thanks for merging!

**Pull request merged**
