### PR TITLE
Upgrade babel deps

### PR DESCRIPTION
**Pull request by kjkta**
For modern builds

### CODE REVIEW

**Comment by misund** [comment]
Thanks for contributing!

I don't really want to upgrade to babel 7 before it comes out of beta. Are you having any issue that this PR fixes?

**Comment by kjkta** [comment]
Agree with you!

I use Babel 7 in my project, and adding hex-to-rgba broke the build -
missing babel-preset-2015 - as it is replaced by @babel/preset-env.

Maybe it could be fixed by using peerDependancies?

In the meantime, it could be useful to release the Babel 7 upgrade under a
branch?

**Comment by misund** [comment]
I'm going to wait for the release. If you want to roll your own in the mean time, something like this in your package.json would do the trick:

`"hex-to-rgba": "github:kjkta/hex-to-rgba#7ee1bdb",`

**Comment by kjkta** [comment]
Yep, no worries :) Already am using it 👍

**Pull request closed without merging**
